include: package:lints/recommended.yaml
analyzer:
  errors:
    unnecessary_getters_setters: ignore
    library_private_types_in_public_api: ignore
    unnecessary_library_name: ignore
    use_super_parameters: ignore
    must_be_immutable: ignore

# linter:
#   rules:
#     - camel_case_types

# analyzer:
#   exclude:
#     - path/to/excluded/files/**