name: statekit
description: Statekit is a powerful state management library for Flutter, designed for efficiency, widget binding, and ease of use.
version: 1.0.0
repository: https://github.com/dharmeshgondaliya/statekit
topics: [statekit, state-management, widget-binding]

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  lints: ^5.0.0
  flutter_test:
    sdk: flutter